import { ClockIcon } from '@heroicons/react/24/outline';
import Head from 'next/head';
import React, { FC } from 'react'
import { BsPinterest, BsTwitter } from 'react-icons/bs';
import { FaFacebookF, FaInstagram, FaPhoneSquareAlt } from 'react-icons/fa';
import { MdEmail } from 'react-icons/md';
import { TbClock } from 'react-icons/tb';
import Footer from './Footer';
import Header from './Header';
import NavBar from './Navbar';

interface IPageComponent {
  title?: string;
  buttons?: any;
  element?: any;
  children?: any
}

const PageLayout: FC<IPageComponent> = ({ title, buttons = '', element, children }) => {
  const truncateString = (str: string, num: number) => {
    if (str.length <= num) {
      return str
    }
    return str.slice(0, num);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
        <div className='sticky top-0 z-20'>
        <div className='w-full'>
          <div className='border-b-[1px] border-gray-200 border-opacity-20 text-white bg-[#0497f3]'>
            <div className='hidden justify-between px-4 py-3 mx-auto lg:max-w-7xl md:items-center md:flex md:px-8'>
              <div className='flex'>
                <BsTwitter className='mr-4'/>
                <FaFacebookF className='mr-4'/>
                <FaInstagram className='mr-4'/>
                <BsPinterest className='mr-4'/>
              </div>
              <div className='flex text-sm'>
                <div className='flex items-center mx-4'>
                  <FaPhoneSquareAlt className='mr-3'/>
                  <p>+234-706-9441-021</p>
                </div>
                <div className='flex items-center mx-4'>
                  <MdEmail className='mr-3'/>
                  <p>contact@amaspace.com</p>
                </div>
                <div className='flex items-center mx-4'>
                  <TbClock className='mr-3'/>
                  <p>9:00 AM - 6:00 PM</p>
                </div>
              </div>
            </div>
          </div>
          <NavBar />
        </div>
      </div>
        </div>
        <div className="">
          {children}
        </div>
        <Footer />
      </main>
    </>
  )
}

export default PageLayout