import Footer from '@/components/Footer'
import Gallery from '@/components/Gallery'
import NavBar from '@/components/Navbar'
import Breadcrum from '@/components/Page/Breadcrum'
import Description from '@/components/Products/Description'
import Reviews from '@/components/Products/Reviews'
import Head from 'next/head'
import React, { useState } from 'react'

const ProductDetail = () => {
  const [selectedNav, setSelectedNav] = useState('DESCRIPTION')

  const navItems: Record<string, any> = {
    DESCRIPTION: {
      name: 'Description',
      value: 'DESCRIPTION',
      component: Description,
    },
    REVIEWS: {
      name: 'Reviews',
      value: 'REVIEWS',
      component: Reviews,
    },
  }

  const nav = navItems[selectedNav];
  const Component = nav.component ?? Description;
  const values = Object.values(navItems);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-white'>
        <div className='bg-white'>
          <NavBar/>
        </div>
        <div className='bg-[url("/assets/bg-section-5.jpg")] bg-no-repeat bg-fixed'>
          <Breadcrum title='our products' name='our products' sub='Hammer'/>
        </div>
        <div className='py-16'>
          <div className='container m-auto px-10'>
            <div className='flex justify-between gap-8 flex-col md:flex-row'>
              <div>
                <div className='w-full'>
                  <div className='mb-3'>
                    <img
                      className='w-full'
                      src='/assets/images/gallery/1.jpg'
                      alt='alt'
                    />
                  </div>
                  <div className='flex justify-between w-full gap-4'>
                    <div className='h-auto'>
                      <img
                        width={200}
                        className=''
                        src='/assets/images/gallery/p-1.jpg'
                        alt='alt'
                      />
                    </div>
                    <div className='h-auto'>
                      <img
                        width={200}
                        className=''
                        src='/assets/images/gallery/p-2.jpg'
                        alt='alt'
                      />
                    </div>
                    <div className='h-auto'>
                      <img
                        width={200}
                        className=''
                        src='/assets/images/gallery/p-3.jpg'
                        alt='alt'
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className='w-full space-y-8'>
                <div className='space-y-2'>
                  <p className='text-4xl font-medium'>AQR2532NNW | S55720-S136</p>
                  <p className='text-gray-400'>AQR2532NNW – Front module for base modules, temperature (active)</p>
                  <div className='flex text-xs'>
                    <p className='text-gray-400 mr-2'>Categories:</p>
                    <div className='flex gap-2'>
                      <a className='hover:underline'>Accessories</a>
                      <p className='hover:underline'>Automation system</p>
                      <p className='hover:underline'>Building Management</p>
                    </div>
                  </div>
                  <div className='flex gap-2 text-sm'>
                    <div className='bg-gray-100 py-2 px-4 shadow hover:bg-[#f3b004] hover:text-white ring-gray-300 ring-1'>
                      <a href="">Add To Cart</a>
                    </div>
                    <div className='bg-gray-100 py-2 px-4 shadow hover:bg-[#f3b004] hover:text-white ring-gray-300 ring-1'>
                      <a href="">Buy Now</a>
                    </div>
                    <div className='bg-gray-100 py-2 px-4 shadow hover:bg-[#f3b004] hover:text-white ring-gray-300 ring-1'>
                      <a href="">Contact Us</a>
                    </div>
                  </div>
                </div>
                <div className='space-y-4'>
                  <div className="flex border-b">
                    {
                      values.map((item, i) => (
                        <div key={i} className="-mb-px mr-1">
                          <a
                            onClick={(e) => setSelectedNav(item.value)}
                            className={`bg-white inline-block ${selectedNav === item.value ? 'border-l border-t border-r rounded-t text-gray-700' : 'text-gray-500 hover:text-[#f3b004]'} py-2 px-4 font-semibold`} href="#"
                          >{item.name}</a>
                        </div>
                      ))
                    }
                  </div>
                  <div>
                    <Component/>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Footer/>
      </main>
    </>
  )
}

export default ProductDetail