import Footer from '@/components/Footer'
import NavBar from '@/components/Navbar'
import Breadcrum from '@/components/Page/Breadcrum'
import ProductCard from '@/components/Products/Card'
import Head from 'next/head'
import React from 'react'

const Products = () => {
  const productsData = [
    {id: 1, img: "/assets/shop-image.png", name: "Product One"},
    {id: 2, img: "/assets/shop-image.png", name: "Product One"},
    {id: 3, img: "/assets/shop-image.png", name: "Product One"},
    {id: 4, img: "/assets/shop-image.png", name: "Product One"},
    {id: 5, img: "/assets/shop-image.png", name: "Product One"},
    {id: 6, img: "/assets/shop-image.png", name: "Product One"},
  ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-white'>
        <div className='bg-white'>
          <NavBar/>
        </div>
        <div className='bg-[url("/assets/bg-section-4.jpg")] bg-no-repeat bg-fixed'>
          <Breadcrum title='our products' name='our products'/>
        </div>
        <div className='py-16'>
          <div className='container m-auto px-10'>
            <div className='flex justify-between gap-4 flex-col md:flex-row'>
              <aside className='bg-gray-200 md:h-screen md:w-[30%]'>

              </aside>
              <section className='md:w-[70%]'>
                <div className='flex justify-between items-center'>
                  <div className='text-gray-600'>
                    <p>Showing 1–6 of 7 results</p>
                  </div>
                  <div>
                    <select className="bg-gray-50 border border-gray-300 text-gray-600 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full p-4">
                      <option selected>Default Sorting</option>
                      <option value="size">Size</option>
                      <option value="color">Color</option>
                      <option value="price">Price</option>
                    </select>
                  </div>
                </div>
                <div className='md:grid md:grid-cols-3 md:gap-8 pt-10 space-y-12'>
                  {
                    productsData.map((product, i) => (
                      <ProductCard key={i} id={product.id} img={product.img} name={product.name} />
                    ))
                  }
                </div>
              </section>
            </div>
          </div>
        </div>
        <Footer/>
      </main>
    </>
  )
}

export default Products